@echo off
echo Iniciando o Sistema de Caixa com PostgreSQL...
echo.
echo Verificando conexao com o banco de dados...
node migrations/test-connection.js
echo.
echo Iniciando o servidor...
node server.js